"""Export both manuscripts' concrete tables from immutable audit evidence.

Run from any directory after the three audit scripts. No fitting, selection,
measurement processing or modification of the original audit files occurs.
Each manuscript includes its own generated files and builds independently.
Only the standard library is required.
"""
from pathlib import Path
import hashlib
import json

PAPER = Path(__file__).resolve().parents[1]
EVIDENCE = PAPER / "docs" / "audit_data"


def table(headers, rows, align):
    return ("\\begin{tabular}{" + align + "}\n\\toprule\n"
            + " & ".join(headers) + " \\\\\n\\midrule\n"
            + "".join(" & ".join(map(str, r)) + " \\\\\n" for r in rows)
            + "\\bottomrule\n\\end{tabular}\n")


def main():
    paths = [EVIDENCE / n for n in ("audit_results.json", "observable_checks.json")]
    audit, observable = [json.loads(p.read_text(encoding="utf-8")) for p in paths]
    slices = audit["slices"]
    hashes = {p.name: hashlib.sha256(p.read_bytes()).hexdigest() for p in paths}
    provenance = "% Generated by numerics/export_audit_tables.py; do not edit.\n"
    provenance += "".join(f"% {name} SHA256 {digest}\n" for name, digest in hashes.items())
    rows, support = [], []
    for s in slices:
        rpm, temp = int(s["rpm"]), int(s["rotor_reference_C"])
        r = s["raw_path_R_ohm"]
        rows.append([rpm, temp, r["n"], f'{s["symmetry_R_ohm"]*1000:.6f}',
                     f'{r["median"]*1000:.6f}', f'{r["raw_mad"]*1000:.6f}',
                     f'{s["exact_path_R_ohm"]["median"]*1000:.6f}'])
        # Counts before the unchanged ten-percent axis filter come from the
        # original study: 2871/69 candidates; expose hull losses explicitly.
        candidates = 2871 if s["dataset"] == "WW_Dataset_Outlier.mat" else 69
        support.append([rpm, temp, f'{s["OP_groups"]}/{s["requested_keys"]}',
                        f'{s["pairs"]}/{s["high_pairs"]}', f'{r["n"]}/{candidates-r["n"]}'])
    comparisons = table([r"$n$", r"$T_{\rm rot,ref}$", r"$N_{\rm rect}$",
                         r"$R_{\rm eq,sym}$", r"$R_{\rm eq,path}$",
                         "MAD", "P1 exact"], rows, "rrrrrrr")
    counts = table([r"$n$", r"$T_{\rm rot,ref}$", "OP/keys", "Pairs/high",
                    "Rectangles/skips"], support, "rrrrr")
    s = next(s for s in slices if s["rpm"] == 2000 and s["rotor_reference_C"] == 60)
    o = next(o for o in observable["symmetry_region"] if o["rpm"] == 2000 and o["temp_C"] == 60)
    metrics = []
    for region, label in (("high", f'High ({s["high_pairs"]} pairs)'),
                          ("all", f'All ({s["pairs"]} pairs)')):
        for key, channel in (("rd_rms_Wb", r"$r_d$ RMS"), ("rq_rms_Wb", r"$r_q$ RMS"),
                             ("vector_rms_Wb", "Vector RMS")):
            metrics.append([label, channel, "mWb", f'{o[region+"_raw"][key]*1000:.6f}',
                            f'{o[region+"_changed_R"][key]*1000:.6f}'])
    path_support = f'{s["raw_path_R_ohm"]["n"]} rectangles'
    metrics += [[path_support, r"Median $\rho_{\rm path}$", r"\%",
                 f'{s["raw_relative_difference"]["median"]*100:.6f}',
                 f'{s["corrected_relative_difference"]["median"]*100:.6f}'],
                [path_support, r"Median $\Delta R_{\rm eq,path}$", r"m$\Omega$",
                 f'{s["raw_path_delta_R_ohm"]["median"]*1000:.6f}',
                 f'{s["corrected_path_delta_R_ohm"]["median"]*1000:.6f}'],
                [path_support, r"Median $R_{\rm eq,path}$", r"m$\Omega$",
                 f'{s["raw_path_R_ohm"]["median"]*1000:.6f}',
                 f'{(s["symmetry_R_ohm"]-s["corrected_path_delta_R_ohm"]["median"])*1000:.6f}']]
    changed = table(["Support", "Metric", "Unit", "Raw", "Adjusted"], metrics, "lllrr")
    for paper in (PAPER, PAPER.parent / "flux_map_error_diagnostics"):
        out = paper / "figures" / "data" / "audit"
        out.mkdir(parents=True, exist_ok=True)
        for name, body in (("slice_comparison.tex", comparisons), ("support.tex", counts),
                           ("raw_adjusted_60.tex", changed)):
            (out / name).write_text(provenance + body, encoding="utf-8")
        (out / "provenance.json").write_text(json.dumps({
            "audit_input_sha256": hashes,
            "exporter_sha256": hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
            "rounding": "six decimal places; resistances mOhm, flux residuals mWb",
            "support": "unchanged audit rectangles and original pair subsets",
        }, indent=2) + "\n", encoding="utf-8")
    print("Exported audit tables for both flux papers without changing evidence.")


if __name__ == "__main__":
    main()
